### ISSUE TITLE
Issue with the Density Volume window

### ISSUE THREAD

**Issue by mathieulinares** [scanberg/viamd#15]
On Ubuntu:
- The density volume window can be interacted with, only if in the viamd window and not outside.
- When using filtering, the density is not updated properly. 

![Screenshot from 2021-11-25 10-47-12](https://user-images.githubusercontent.com/38646069/143418628-3220b332-aa27-41fd-af5b-72cfe0a24d1c.png)

**Comment by scanberg** [comment]
Should not be resolved.
