### ISSUE TITLE
Crash when clicking the windows on startup while it's not fully loaded

### ISSUE THREAD

**Issue by k2d222** [scanberg/viamd#22]
I get the following assert failure when I click on the window shortly after the program started, and before the imgui panels appear:

```
viamd/src/main.cpp:7451: void handle_camera_interaction(ApplicationData*): Assertion `data->picking.idx <= data->mold.mol.atom.count' failed.
```

**Comment by k2d222** [comment]
looks like it doesn't crash when running on the Nvidia gpu, only on the Ryzen integrated gpu.
Also I should have noted that I compiled and run on linux.

**Comment by scanberg** [comment]
Changed the assertion into a softer if check ([4ffc589](https://github.com/scanberg/viamd/commit/4ffc589f9b7d06954ebea03be3b6437eba908cce)), but the underlying issue of atom indices read from GPU buffer not being in valid range on Ryzen probably requires further investigation. However, I do not have any hardware available to test it out currently.
