### ISSUE TITLE
md_benchmark Assertion "file" failed at line 436

### ISSUE THREAD

**Issue by mcbeaker** [scanberg/viamd#42]
Hiya! I am thrilled to be using VIAMD, I am hopeful this will spread widely. I installed VIAMD and I attached the cmake output. I tried to run the md_benchmark script that you provide, however  I got the following error. Thanks for your help! Please let me know any additional info you need me to provide, such as GPU info (which I added below the error)
 
[viam-cmake-output.txt](https://github.com/scanberg/viamd/files/13528033/viam-cmake-output.txt)

./md_benchmark 
name                       min iter time (ms)       min elem time (ns)        throughput (MB/s)
Speed of light                           1.18                     0.37                 14617.27
com_min_image_ref                       65.07                    20.68                   264.04
com_trig_ref                            71.02                    22.58                   241.90
com_min_image_sse                       37.02                    11.77                   464.09
com_trig_sse                           100.31                    31.89                   171.27
com_min_image_avx2                      20.20                     6.42                   850.48
com_trig_avx2                           48.43                    15.39                   354.75
com_min_image_avx512                     8.29                     2.63                  2072.94
com_trig_avx512                         21.73                     6.91                   790.77
[==========] Running 20 benchmarks.
[ RUN      ] allocator.default
[       OK ] allocator.default (mean 0.137us, confidence interval +- 0.466282%) 
[ RUN      ] spatial_hash.init_regular
[       OK ] spatial_hash.init_regular (mean 32.125ms, confidence interval +- 0.248376%) 
[ RUN      ] spatial_hash.init_periodic
[       OK ] spatial_hash.init_periodic (mean 43.887ms, confidence interval +- 0.554247%) 
[ RUN      ] spatial_hash.query_regular
[       OK ] spatial_hash.query_regular (mean 176.643ms, confidence interval +- 0.283656%) 
[ RUN      ] spatial_hash.query_periodic
[       OK ] spatial_hash.query_periodic (mean 623.137ms, confidence interval +- 0.121939%) 
[ RUN      ] spatial_hash.query_regular_batch
[       OK ] spatial_hash.query_regular_batch (mean 23.075ms, confidence interval +- 0.220998%) 
[ RUN      ] spatial_hash.query_periodic_batch
[       OK ] spatial_hash.query_periodic_batch (mean 55.391ms, confidence interval +- 0.337296%) 
[ RUN      ] spatial_hash.query_bruteforce
[       OK ] spatial_hash.query_bruteforce (mean 429.741ms, confidence interval +- 0.083010%) 
[ RUN      ] xtc.load
[09:54:09][info]:  XTC: Attempting to create new cache file...
[09:54:09][info]:  XTC: Successfully created cache file for trajectory
[       OK ] xtc.load (mean 39.751ms, confidence interval +- 0.092922%) 
[ RUN      ] gro.load
[       OK ] gro.load (mean 27.231ms, confidence interval +- 1.384718%) (267.283 MB/s)
[ RUN      ] pdb.dppc64
[       OK ] pdb.dppc64 (mean 3.129ms, confidence interval +- 0.069364%) (315.577 MB/s)
[ RUN      ] pdb._100frames
Assertion "file" failed at line 436 in /home/ken/software/viamd/ext/mdlib/src/core/md_os.c:md_file_size
Illegal instruction (core dumped)

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0

nvidia-smi
Fri Dec  1 10:01:02 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:01:00.0  On |                  Off |
|  0%   50C    P8              18W / 450W |    465MiB / 24564MiB |      4%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off | 00000000:03:00.0 Off |                  Off |
|  0%   47C    P8              14W / 450W |     14MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3286      G   /usr/lib/xorg/Xorg                          149MiB |
|    0   N/A  N/A      3403      G   /usr/bin/gnome-shell                         53MiB |
|    0   N/A  N/A      3858      G   ...sion,SpareRendererForSitePerProcess      111MiB |
|    0   N/A  N/A     13099      G   ...RunOnOsLogin,WebAssemblyTrapHandler      132MiB |
|    1   N/A  N/A      3286      G   /usr/lib/xorg/Xorg                            4MiB |

**Comment by mathieulinares** [comment]
Thanks for your kind message @mcbeaker. We are aware of this segmentation fault during the md_benchmark. May I ask if the application viamd is running smoothly otherwise?

**Comment by mcbeaker** [comment]
@mathieulinares thank you for your prompt response, great to hear your on top of this segmentation fault. In regards to the application running smoothly, I think there are some rendering hiccups that I am not sure if they are a user error, or if it is because i am using a 49' curved monitor Samsung Odyssey G9. 
![IMG_8782](https://github.com/scanberg/viamd/assets/2272762/766d4201-ff65-40b8-93c9-80e84078f13a)

**Comment by mathieulinares** [comment]
First of all, I want the same at home. where you the one that change the background color to black or did it happened by default?

**Comment by mcbeaker** [comment]
https://a.co/d/54x3BFn - I wouldn't recommend it because of the resolution when displaying my Mac M2 2023, however by itself on PopOs, it isn't terrible. I ordered the https://a.co/d/bEMWdEm because the aspect ratio is 21:9 and is 5k (width) by 2k (height) resolution. With the https://a.co/d/54x3BFn you can see pixels. https://a.co/d/0KcPx2O spoiled me

**Comment by scanberg** [comment]
I made a pass over the benchmarks to ensure that they fail gracefully if the test files are not present.
