### ISSUE TITLE
Add desktop file

### ISSUE THREAD

**Issue by bkmgit** [scanberg/viamd#48]
Linux desktop applications typically use a desktop file. Could one be added? Can also create a pull request to add one. Some references:
- https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
- https://wiki.archlinux.org/title/Desktop_entries
- https://docs.fedoraproject.org/en-US/packaging-guidelines/#_desktop_files

**Comment by scanberg** [comment]
Hi @bkmgit,
This has been discussed at some point in the past but has not been deemed a high priority. If you would be willing to help us out here, we would be very grateful!

Best regards,
Robin
