### ISSUE TITLE
Helix and sheet scale labels are swapped in cartoon representation

### ISSUE THREAD

**Issue by Derivolate** [scanberg/viamd#52]
In the representations window when viewing a protein in cartoon style, the labels for the helix scale and sheet scale sliders are swapped.

**Comment by scanberg** [comment]
@Derivolate Thanks for pointing this out. I can verify that it was certainly the case and it's now fixed in [533bf67](https://github.com/scanberg/viamd/commit/533bf6798003d7c929a56d46d47934a274581b6a).
Thanks again for pointing this out.

Best,
Robin
