### ISSUE TITLE
Grow radial selection does not work - Windows v0.1.32

### ISSUE THREAD

**Issue by Eduardneu** [scanberg/viamd#60]
Hi,

Unfortunately, after I selected the ligand with shift + left click and did the radial grow it did not expand my selection. I don't know if this is a bug. I used the version v0.1.32.

I noticed that this is system dependent. So for one system with 2 ligands and 2 protein chains it did not work while for another system it did work. 

Best
Eddie

**Comment by scanberg** [comment]
Just wanted to be transparent to other users here. Eddie contacted us over mail, and the issue seemed to be related to the dataset which was concatenated using cpptraj. When performing the concatenation using gromacs tools, it seemed to work.

Will close this issue for now. But if the issue emerges again the issue might be revived.
