### ISSUE TITLE
Loading LAMMPS data file with nb_angles > nb_dihedrals

### ISSUE THREAD

**Issue by nicro31** [scanberg/viamd#62]
Hi Robin !

I noticed an issue when trying to load LAMMPS data file in specific cases where the number of angles in the topology is higher than the number of dihedrals.

In that case, VIAMD fails to parse angles with the following error : [error]: Failed to parse angle line, expected 5 tokens, got 0 [parse_angles]

I suspect that there is a small bug in mdlib/src
/md_lammps.c
I think that when parsing the dihedrals (from line 570), functions corresponding to angles parsing are called instead of dihedrals ones.

Cheers !
Nicolas

**Comment by scanberg** [comment]
Hi Nicolas!

Thanks for the find, copy pasta all over the place!
I'll get it fixed and update the tests as well. They could be more elaborate.

Best,
Robin

**Comment by scanberg** [comment]
The latest version ([984ec59](https://github.com/scanberg/viamd/commit/984ec5928cfd3d8502a7d195c5bb46c254e255c4)? should contain the fixes. Keep me up to date whenever you find another :)
