### ISSUE TITLE
Proble compiling the 0.1.32 version

### ISSUE THREAD

**Issue by xavgit** [scanberg/viamd#63]
Hi,
I'm upgrading to the latest version , 0.1.32, and I'm receiving
the following output error:
\:~/sources/viamd-0.1.32$ mkdir build
:~/sources/viamd-0.1.32$ cd build
:~/sources/viamd-0.1.32/build$ cmake ..
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:5 (INCLUDE):
  INCLUDE could not find requested file:

    ext/mdlib/cmake/common.cmake

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
CMake Error at CMakeLists.txt:40 (add_subdirectory):
  The source directory

    /home/xxxx/sources/viamd-0.1.32/ext/mdlib

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:41 (add_subdirectory):
  The source directory

    /home/xxxx/sources/viamd-0.1.32/ext/glfw

  does not contain a CMakeLists.txt file.

-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:45 (add_subdirectory):
  The source directory

    /home/xxxx/sources/viamd-0.1.32/ext/enkiTS

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:114 (create_resources):
  Unknown CMake command "create_resources".

-- Configuring incomplete, errors occurred!

I use Ubuntu 20.04.

Thanks.
Saverio

**Comment by scanberg** [comment]
Hi Saverio,

Thanks for pointing this out.
The script for generating the source code packages for the releases seem to ignore the git submodules.
I'll take a look and see what I can do.

In the meantime, I would recommend you to fetch the latest version via git manually:
`git clone --recurse-submodules https://github.com/scanberg/viamd.git`
To make sure you get the submodules included. 

Best regards,
Robin

**Comment by xavgit** [comment]
Hi Robin,
thanks.
All is fine.

Saverio
