### ISSUE TITLE
Compiling error on linux

### ISSUE THREAD

**Issue by qzchen2022** [scanberg/viamd#65]
Hi,

I trired to compile VIAMD with gcc12. It seems like it failed during test as :

____
[ 69%] Building C object ext/mdlib/unittest/CMakeFiles/md_unittest.dir/test_util.c.o
viamd/ext/mdlib/unittest/test_util.c: In function ‘utest_run_util_rmsd’:
viamd/ext/mdlib/unittest/test_util.c:145:40: error: passing argument 1 of ‘md_util_rmsd_compute’ from incompatible pointer type [-Wincompatible-pointer-types]
  145 |     double rmsd = md_util_rmsd_compute(x, y, z, w, 0, mol->atom.count, com);
      |                                        ^
      |                                        |
      |                                        float **
In file included from viamd/ext/mdlib/unittest/test_util.c:9:
viamd/ext/mdlib/src/md_util.h:173:48: note: expected ‘const float * const*’ but argument is of type ‘float **’
  173 | double md_util_rmsd_compute(const float* const in_x[2], const float* const in_y[2], const float* const in_z[2], const float* in_w, const int32_t* in_idx, size_t count, const vec3_t in_com[2]);
      |                             ~~~~~~~~~~~~~~~~~~~^~~~~~~
/viamd/ext/mdlib/unittest/test_util.c:145:43: error: passing argument 2 of ‘md_util_rmsd_compute’ from incompatible pointer type [-Wincompatible-pointer-types]
  145 |     double rmsd = md_util_rmsd_compute(x, y, z, w, 0, mol->atom.count, com);
      |                                           ^
      |                                           |
      |                                           float **
/viamd/ext/mdlib/src/md_util.h:173:76: note: expected ‘const float * const*’ but argument is of type ‘float **’
  173 | double md_util_rmsd_compute(const float* const in_x[2], const float* const in_y[2], const float* const in_z[2], const float* in_w, const int32_t* in_idx, size_t count, const vec3_t in_com[2]);
      |                                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~
/viamd/ext/mdlib/unittest/test_util.c:145:46: error: passing argument 3 of ‘md_util_rmsd_compute’ from incompatible pointer type [-Wincompatible-pointer-types]
  145 |     double rmsd = md_util_rmsd_compute(x, y, z, w, 0, mol->atom.count, com);
      |                                              ^
      |                                              |
      |                                              float **
/viamd/ext/mdlib/src/md_util.h:173:104: note: expected ‘const float * const*’ but argument is of type ‘float **’
  173 | double md_util_rmsd_compute(const float* const in_x[2], const float* const in_y[2], const float* const in_z[2], const float* in_w, const int32_t* in_idx, size_t count, const vec3_t in_com[2]);
      |                                                                                     ~~~~~~~~~~~~~~~~~~~^~~~~~~
ext/mdlib/unittest/CMakeFiles/md_unittest.dir/build.make:299: recipe for target 'ext/mdlib/unittest/CMakeFiles/md_unittest.dir/test_util.c.o' failed

____

But I can open it under the /build/bin

![image](https://github.com/scanberg/viamd/assets/110490187/67d51adb-2772-4b45-973b-880694c5d073)

**Comment by qzchen2022** [comment]
I change the codes at 145 line of /viamd/ext/mdlib/unittest/test_util.c

from
`
double rmsd = md_util_rmsd_compute(x, y, z, w, 0, mol->atom.count, com);
`
to

```
    const float* const tmp_x[2] = {x[0], x[1]};
    const float* const tmp_y[2] = {y[0], y[1]};
    const float* const tmp_z[2] = {z[0], z[1]};

    double rmsd = md_util_rmsd_compute(tmp_x, tmp_y, tmp_z, w, 0, mol->atom.count, com);
    
```

Now it compilled.

**Comment by scanberg** [comment]
Thanks for pointing this out, I've seen related warnings of this before, but not any concrete errors. I have resolved the issue in the latest commit.

Best regards,
Robin
