### ISSUE TITLE
ChainIDs in script language and representations

### ISSUE THREAD

**Issue by DavidCdeB** [scanberg/viamd#72]
Thanks again for this program.

We've identified a potential bug on how VIAMD script shows and manages residues using the ChainIDs.

**MWE:**
(`.via` and `.gro` attached in a zip file).
Let's say I have this script:
```
ASP_253_Chain_B = resname("ASP") and resid(253) and chain("B");
GLU_123_Chain_B = resname("GLU") and resid(123) and chain("B");
```
Even though both use the same logic, one can visualize `ASP_253_Chain_B` but not `GLU_123_Chain_B`:
[files.zip](https://github.com/user-attachments/files/15765006/files.zip)

![issue_viamd](https://github.com/scanberg/viamd/assets/18029016/f567ec2f-aa16-48fb-a19e-548f8c4cbf78)

**Comment by scanberg** [comment]
@DavidCdeB: Thanks for the report David! And thanks for sharing the data, it certainly helps in debugging.
I'll look into it when I get a chance.

Best,
Robin

**Comment by scanberg** [comment]
Hi @DavidCdeB 
I pushed a fix just now on master. Mathieu encountered a similar issue which I believe to be the same fundamental bug.
I'll keep the issue open for now until you have a chance to test and assert that it fixed your issue as well.

Best regards,
Robin

**Comment by DavidCdeB** [comment]
Hi @scanberg 
Many thanks for looking into it!, the fix on master does work.
All the best,
David
