### ISSUE TITLE
Bug on additions and substractions in script editor

### ISSUE THREAD

**Issue by DavidCdeB** [scanberg/viamd#75]
I'm trying to program equations in the script editor that require summing and/or subtracting distances, and I encountered the editor has some difficulties in interpreting such math operations.

I've reduced this thread to a Minimal Working Example, of the type `a + b - c - d` operation, however this escalates when the formula in question is more complex. 

Over the peptide opened by default when launching VIAMD:

```
dist1 = distance(111, 105);
dist2 = distance(103, 101);

var = dist1 + dist2 - dist1 - dist2;  # does not work as expected since it does not give a distribution equal to zero.

var2 = (dist1 + dist2);
var3 = (dist1 + dist2);
block = var2 - var3; # works as expected since it gives a distribution equal to zero.
```

`var` does not work as expected since it does not give a distribution equal to zero.

Distributions:
![var](https://github.com/user-attachments/assets/d4ca2c81-2771-4f7a-8536-d7d37a10453a)

**Comment by scanberg** [comment]
@DavidCdeB Thanks for the report! I'll look into it.

**Comment by scanberg** [comment]
@DavidCdeB Thanks again for the report.
The issue should be solved in the latest commit.

Best
Robin

**Comment by DavidCdeB** [comment]
@scanberg Many thanks, that worked.
Best,
David
