### ISSUE TITLE
Wrong atom colouring with PDP trajectory

### ISSUE THREAD

**Issue by BastiaanvHoorn** [scanberg/viamd#79]
Hi,

When loading a PDB trajectory, some of my atoms get wrongly identified and coloured, as well as showing glitchy movement which is not present in the actual trajectory. In the example, one special water residue (REA) gets identified wrongly as Rhodium, Silver and Cobalt, and one atom in my graphene sheet gets identified as Terbium. These atoms are the first 4 atoms in my PDB. The rest of the trajectory, including all other water molecules, get rendered fine. See the attached PDB file as well as the code snippet and the attached screenshot.

```
HETATM    1  H0  REA A   1      21.192   2.532   4.764  1.00  0.00           H  <- wrong
HETATM    2  H1  REA A   1      19.852   2.304   5.473  1.00  0.00           H <- wrong 
HETATM    3  O2  REA A   1      20.324   2.094   4.623  1.00  0.00           O  <- wrong
HETATM    4 0    CCC A   2       0.838   1.331  10.758  1.00  0.00           C  <- wrong
HETATM    5 1    CCC A   2       1.540   0.078  10.783  1.00  0.00           C  <- fine from here
HETATM    6 2    CCC A   2       3.026   0.057  10.692  1.00  0.00           C  
HETATM    7 3    CCC A   2       3.744   1.269  10.848  1.00  0.00           C  
....
HETATM  182 178  CCC A   2      20.007  19.803  11.074  1.00  0.00           C  
HETATM  183 179  CCC A   2      20.786  20.969  10.752  1.00  0.00           C   <- End of graphene sheet
HETATM  184  O0  SOL A   3       2.569   3.775  19.259  1.00  0.00           O  <- beginning of rest of the water molecules
HETATM  185  H1  SOL A   3       2.437   3.462  20.201  1.00  0.00           H  
HETATM  186  H2  SOL A   3       2.553   4.738  19.423  1.00  0.00           H  
HETATM  187  O0  SOL A   4       0.262   9.710   1.477  1.00  0.00           O  
HETATM  188  H1  SOL A   4       0.594   9.720   2.406  1.00  0.00           H  
HETATM  189  H2  SOL A   4       0.887  10.243   0.962  1.00  0.00           H  
```

![Screenshot 2024-10-24 at 12 21 07](https://github.com/user-attachments/assets/7bb87f6f-5c23-470c-a63d-d70578895a60)

Is this caused by how I have generated the PDB file, or is this due to a bug in ViaMD?

[Trajectory.pdb.txt](https://github.com/user-attachments/files/17505331/Trajectory.pdb.txt)

**Comment by scanberg** [comment]
Hi @BastiaanvHoorn,

Thanks for the report and for providing the trajectory.
It's most certainly a bug within VIAMD.
Are you running the latest release btw?

Best,
Robin

**Comment by scanberg** [comment]
@BastiaanvHoorn 

This is an old issue that I thought I had resolved. But alas, it was not correctly fixed.
I made some changes to make it more robust and it should now function properly I hope.

Best,
Robin
